.eslintignore, .eslintrc.json, .husky/pre-commit, .lintstagedrc.js, .prettierignore, package-lock.json, package.json
Add precommit using husky to enforce lint and prettier rules
Added precommit using husky to enforce lint and prettier rules
By feeling
NA
=> Adding husky, precommit

.babelrc, __tests__/integration/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/landing-page/__snapshots__/page.test.tsx.snap, __tests__/integration/landing-page/layout.test.tsx, __tests__/integration/landing-page/page.test.tsx, jest.config.ts, package-lock.json, package.json, src/app/(landing-page)/page.tsx, src/components/global/Footer.tsx, src/components/global/Header.tsx, src/components/global/Logo.tsx, src/components/landing-page/Header.tsx, tsconfig.json
Should've done it earlier lol.
Add jest setup for unit and integration test.
Also add some tests to verify that it is working as expected.
Added jest setup.
And added some tests.
By writing tests BC.
NA
=> Adding jest test setup

.env, .gitignore
The env file was mistakenly pushed here. Since it had no critical information, all good as of now.
Removed it and updated the gitignore accordingly.
=> Removed unnecessary files

src/app/(enter-data)/enter-data/page.tsx, src/components/global/form/form-sections/Additional.tsx, src/lib/types/form.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/18
- All the input fields should work.
- The big delete button on top deletes the whole section.
Added the additional section and made the relevant changes for it
(Similar to the previous sections so not adding much details here)
Tested the UI locally
| Theme| Image |
| -- | -- |
| Light | ![image](https://github.com/amlan-roy/resume-craft/assets/59330872/c2482fca-c692-4a2a-ba1a-f6d05f6b5d12) | 
| Dark| ![image](https://github.com/amlan-roy/resume-craft/assets/59330872/879a2c08-277d-45db-880c-80d3bbad59ef) |
=> Added the additional section

__tests__/integration/app/enter-data/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/components/global/__snapshots__/footer.test.tsx.snap, src/components/global/Footer.tsx
https://github.com/amlan-roy/resume-craft/issues/29
Open Footer Links in New Tab
add target="_blank" to <Link> component in Footer
Ran locally, tested links do pop open in new tab
https://github.com/amlan-roy/resume-craft/assets/68050609/bf05871f-a5ea-45de-90c0-7bcc0c9d832a
=> Footer Links Open New Tab

.github/CODEOWNERS
This repo does not have a code owners file yet. Need to add it.
Added a `CODEOWNERS` file and added myself as the global code owner.
=> Added myself as the global code owner

__tests__/integration/app/enter-data/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/components/global/__snapshots__/footer.test.tsx.snap, src/app/(enter-data)/enter-data/page.tsx, src/app/(home-page)/home/page.tsx, src/app/(home-page)/layout.tsx, src/components/global/Footer.tsx
Add a temporary home page to navigate to have the basic functionality to navigate to different routes.
- Added a temporary home page with a few buttons
- Update the enter data page text copies
- Update the footer to have a fixed position at the bottom of the page
- Updated the snapshots according to the changes
The home page UI is temporary as I have not yet created a Figma design for it yet. Want to keep it simple, but will still need to update it later on. Created an issue https://github.com/amlan-roy/resume-craft/issues/36 to track this
Tested the UI by locally running the repo
Existing tests pass
Baaki Ram bharose
=> Added home page

README.md
Issue: https://github.com/amlan-roy/resume-craft/issues/49
A descriptive PR should be available.
Added a basic readme. Can be made more descriptive later.
I don't write buggy code so I don't need to test my changes.
=> Adding basic readme

__tests__/integration/app/enter-data/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/components/global/__snapshots__/footer.test.tsx.snap, src/app/(enter-data)/layout.tsx, src/app/(generate-resume)/layout.tsx, src/app/(home-page)/layout.tsx, src/app/(landing-page)/layout.tsx, src/app/layout.tsx, src/components/global/Footer.tsx
Issue: #48
This fixes issue #48
The footer is fixed at bottom of viewport and overlaps the other elements. We want them to be at the bottom of the whole page, not fixed to the bottom of the viewport.
Added tailwind classes to ensure main component takes 100% of viewport and used `flex` classes to convert component into flex containers.
https://github.com/amlan-roy/resume-craft/assets/59330872/2606e3c9-5ab4-4e1e-b563-a87738ab071f
=> fix: update footer to not be fixed to bottom of viewport

__tests__/integration/app/enter-data/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/enter-data/layout.test.tsx, __tests__/integration/app/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/landing-page/layout.test.tsx, __tests__/integration/components/global/__snapshots__/footer.test.tsx.snap, __tests__/integration/components/global/__snapshots__/header.test.tsx.snap, __tests__/integration/components/global/footer.test.tsx, __tests__/integration/components/global/icon.test.tsx, __tests__/integration/components/landing-page/__snapshots__/header.test.tsx.snap, __tests__/integration/components/landing-page/header.test.tsx, src/app/(enter-data)/enter-data/page.tsx, src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(generate-resume)/generate-resume/base/page.tsx, src/app/(home-page)/home/page.tsx, src/app/api/ai-prompts/route.ts, src/app/api/data-formatting/route.ts, src/components/generate-resume/variant/StepFour.tsx, src/components/generate-resume/variant/StepOne.tsx, src/components/generate-resume/variant/StepThree.tsx, src/components/generate-resume/variant/StepTwo.tsx, src/components/global/Logo.tsx, src/components/landing-page/Header.tsx, src/lib/types/form.ts, src/lib/utils/data-formatting.ts, src/middleware.ts, tailwind.config.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/51, https://github.com/amlan-roy/resume-craft/issues/46
Detailed in the ticket descriptions.
Tested locally
=> Adding resume gen for variants

src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(generate-resume)/generate-resume/base/page.tsx, src/app/api/data-formatting/route.ts, src/components/generate-resume/variant/StepTwo.tsx, src/lib/services/resume-service.ts, src/lib/utils/firebase/database/users.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/57
- Using firebase for authentication (tracked as a part of this issue: https://github.com/amlan-roy/resume-craft/issues/56)
- For authenticated users, triggering firebase function (probably using http) to create a resume PDF (Will have to write code for generating pdf from json)
- This created resume will be then stored in firebase file storage.
- The download link of this file will be sent back (either by the same firebase function or a different function/way)
Sleepy so won't write this.
Tested UI locally
=> updated the form submission logic

src/app/(enter-data)/enter-data/page.tsx, src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(generate-resume)/generate-resume/base/page.tsx, src/app/api/data-formatting/route.ts, src/components/generate-resume/variant/StepTwo.tsx, src/components/global/form/DynamicFormLoading.tsx, src/lib/services/resume-service.ts, src/lib/types/form.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/62
As described in the issue description
Modified the code to avoid using local storage, and made other required adjustments
Updated the components as well as per the requiremets
**NOTE**: The code flog might be buggy, did not get a chance to check the whole flow. Need to do a bug bash for this.
Tested the code locally.
=> Modified the code to avoid using local storage, and made other required adjustments

src/app/(home-page)/home/page.tsx, src/app/(my-resumes)/layout.tsx, src/app/(my-resumes)/my-resumes/page.tsx, src/lib/services/resume-service.ts, src/lib/types/resume-response.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/58
Added the page and the methods required
Tested the changes locally
=> added the past generated resumes page and mechanism

src/app/(generate-resume)/generate-resume/base/page.tsx, src/app/(my-resumes)/my-resumes/page.tsx, src/app/api/data-formatting/route.ts, src/lib/services/resume-service.ts
Issue: https://github.com/amlan-roy/resume-craft/issues/58
Added delete api route
fixed some bugs for resume gen, view and delete logic
also made changes in the backend
Tested the UX locally
=> Add delete api route and bug fixes

src/components/global/form/DynamicForm.tsx, src/components/global/form/form-sections/Education.tsx, src/components/global/form/form-sections/Projects.tsx, src/components/global/form/form-sections/Skills.tsx, src/components/global/form/form-sections/WorkExperience.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/25
Fix the error bug
Manually triggering validation (if some error already exists in the form) on deleting section/sub section.
Tested the flow locally.
=> Fix error bug

next.config.js, src/app/(home-page)/home/page.tsx, src/app/api/(auth)/login/route.tsx, src/components/auth/login/LoginForm.tsx, src/middleware.ts
The generate variant page had a static URL (probably set at server). Made it dynamic using middleware
=> fix: fix bug in generate variant page

next.config.js, src/app/api/(auth)/login/route.tsx, src/components/auth/login/LoginForm.tsx
Some debugging code was added in the previous code. Removing that code here.
=> remove unused code used for debugging

src/app/(home-page)/home/page.tsx, src/components/landing-page/Header.tsx, src/middleware.ts
=> fix: gen variant page issue

src/app/(home-page)/home/page.tsx, src/components/landing-page/Header.tsx, src/middleware.ts
Reverts amlan-roy/resume-craft#82
=> Revert "fix: gen variant page issue"

src/app/(home-page)/home/page.tsx, src/components/landing-page/Header.tsx, src/middleware.ts
=> fix: removed the logic from middleware and added directly in page

__tests__/integration/app/enter-data/__snapshots__/layout.test.tsx.snap, __tests__/integration/app/landing-page/__snapshots__/layout.test.tsx.snap, __tests__/integration/components/landing-page/__snapshots__/header.test.tsx.snap
=> updated snapshots

src/components/auth/login/LoginForm.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/77
The issue is not reproducible in the local env. Hence testing the changes in deployed environment using this PR
=> fix: fix other nav issue

src/app/(home-page)/home/page.tsx, src/components/auth/GoogleJoinButton.tsx, src/components/auth/login/LoginForm.tsx, src/components/auth/signup/SignupForm.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/77
using refresh instead of route push
=> Fix login issue

.github/workflows/pr-description-check.yml, __tests__/integration/components/loading/box-loader.test.tsx, src/app/(auth)/loading.tsx, src/app/globals.css, src/components/index.css, src/components/loading/BoxLoader.tsx, src/components/loading/styles/box-loader.css, src/components/loading/styles/index.css
Issue: 
**Note:** Skipping creating an issue is not advised
Added the Box loader component, tests and used that for auth loading page
Tested the changes locally
Added tests
Tests pass
https://github.com/amlan-roy/resume-craft/assets/59330872/a40e0189-177f-497b-8a44-983ca17606c3
=> Add loading

src/app/(auth)/layout.tsx, src/app/(auth)/loading.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/104
Made style updates
Tested the UI locally.
Tests pass.
=> Fix the loading UI for auth flow

src/app/(auth)/loading.tsx, src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(generate-resume)/generate-resume/base/page.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/106
Guarded the resume generation for people with verified email
- Tested UI
- Local tests pass
- Need to add tests (Will add later  --\_(-_-)_/-- )
=> Guarded the resume generation for people with verified email

src/app/(home-page)/layout.tsx, src/app/(my-resumes)/layout.tsx, src/app/(my-resumes)/loading.tsx, src/app/(my-resumes)/my-resumes/page.tsx, src/components/global/AuthenticatedHeader.tsx, src/components/global/form/form-sections/Additional.tsx, src/components/global/form/form-sections/BasicDetails.tsx, src/components/global/form/form-sections/Education.tsx, src/components/global/form/form-sections/Loading.tsx, src/components/global/form/form-sections/ProfessionalSummary.tsx, src/components/global/form/form-sections/Projects.tsx, src/components/global/form/form-sections/Skills.tsx, src/components/global/form/form-sections/WorkExperience.tsx
Updated the forms UI to add a label to the section title field.
Some minor changes
Tested the UI locally
=> Update forms UI

src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(generate-resume)/generate-resume/base/page.tsx, src/app/(my-resumes)/layout.tsx, src/app/(my-resumes)/my-resumes/page.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/69
Refactored the UI
Added error UI (Toasting), loading UI in the delete buttons
Tested locally
=> Update resume view page

src/app/layout.tsx, src/components/global/AuthenticatedHeader.tsx, src/components/providers/user-data-store-provider.tsx, src/lib/stores/user/userStore.ts
Issue:
- Added global user state in zustand
- Used in authenticated header to show the email verification banner and to show the logout button
- Used the store by wrapping it in a provider as suggested in the official docs of zustand
Locally tested the UI
Local tests pass
=> Added global user state

src/components/global/form/form-sections/Additional.tsx, src/components/global/form/form-sections/BasicDetails.tsx, src/components/global/form/form-sections/Education.tsx, src/components/global/form/form-sections/ProfessionalSummary.tsx, src/components/global/form/form-sections/Projects.tsx, src/components/global/form/form-sections/SectionTemplate.tsx, src/components/global/form/form-sections/Skills.tsx, src/components/global/form/form-sections/WorkExperience.tsx
Issue:
This PR introduces a new SectionTemplate component and integrates it into the existing section components. The goal of these changes is to improve code reusability and maintainability.
The following sections have been refactored to use the new SectionTemplate component:
- Additional
- Basic Details
- Education
- Professional Summary
- Projects
- Skills
- Work Experience
Tested the changes locally
Existing tests pass
=> Created and used a section template component

src/app/(home-page)/home/page.tsx
Issue: https://github.com/amlan-roy/resume-craft/issues/127
Remove test experiment
=> Cleanup test experiment

docs/development/experiments.md, src/app/(enter-data)/enter-data/page.tsx, src/app/(generate-resume)/generate-resume/[slug]/page.tsx, src/app/(home-page)/home/page.tsx, src/components/global/AuthenticatedHeader.tsx, src/components/global/form/DynamicForm.tsx, src/components/global/form/modal-state-provider.tsx, src/lib/services/resume-service.ts, src/lib/types/resume-response.ts, src/lib/utils/firebase/database/users.ts
Issue:
This pull request includes several changes to improve the handling of user data and optimize the use of the `useEffect` hook across the codebase. The most important changes are the addition of user data fetching, updates to the `useEffect` hook to include dependency arrays, and modifications to the resume service to accept optional user data. 
* [`src/lib/utils/firebase/database/users.ts`](diffhunk://#diff-aecdebe251994167b32f8b5fce0891cc3b63061682be31b96298fdd1391d803bR63-R73): Added a new function `getUserData` to fetch user data from the database.
* [`src/app/(enter-data)/enter-data/page.tsx`](diffhunk://#diff-d4903f9ed497fd41e52a08991394e31a4d2b99b797bd6b9f327832a44e33420eL62-R64): Integrated `getUserData` to fetch user data before calling `getResumeFormData`. …
=> Add credits and refactor

package-lock.json, package.json, src/components/global/form/DynamicForm.tsx, src/components/global/form/Task.tsx
=> fixed the scroll issue on phone
